#!/bin/sh

# install a LED heartbeat trigger for first 'user' LED
uci -q show system.@led[0] || {
	led=
	for i in $(ls /sys/class/leds); do
		case $i in
			user*)
				[ "$led" ] || led=$i
				;;
		esac
	done
	[ "$led" ] && {
  	uci add system led
  	uci set system.@led[0].default=0
  	uci set system.@led[0].name=heartbeat
  	uci set system.@led[0].sysfs=$led
  	uci set system.@led[0].trigger=heartbeat
  	uci commit
	}
}
